In [59]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import csv
import sklearn 
import graphviz
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from io import StringIO
import sklearn.tree as tree
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import sqlite3
import pandas as pd
import numpy as np
import seaborn as sns
import itertools
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score
from sklearn.calibration import CalibratedClassifierCV
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer
from time import time
from sklearn.decomposition import PCA, FastICA
from sklearn.pipeline import Pipeline
import warnings
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [60]:
traind=pd.read_csv('train.csv')
testd=pd.read_csv('test.csv')

In [61]:
traind.head(2)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  

[2 rows x 81 columns]

In [62]:
for i in traind.columns:
    print(i)
    print(traind[i].unique())

Id
[   1    2    3 ... 1458 1459 1460]
MSSubClass
[ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]
MSZoning
['RL' 'RM' 'C (all)' 'FV' 'RH']
LotFrontage
[ 65.  80.  68.  60.  84.  85.  75.  nan  51.  50.  70.  91.  72.  66.
 101.  57.  44. 110.  98.  47. 108. 112.  74. 115.  61.  48.  33.  52.
 100.  24.  89.  63.  76.  81.  95.  69.  21.  32.  78. 121. 122.  40.
 105.  73.  77.  64.  94.  34.  90.  55.  88.  82.  71. 120. 107.  92.
 134.  62.  86. 141.  97.  54.  41.  79. 174.  99.  67.  83.  43. 103.
  93.  30. 129. 140.  35.  37. 118.  87. 116. 150. 111.  49.  96.  59.
  36.  56. 102.  58.  38. 109. 130.  53. 137.  45. 106. 104.  42.  39.
 144. 114. 128. 149. 313. 168. 182. 138. 160. 152. 124. 153.  46.]
LotArea
[ 8450  9600 11250 ... 17217 13175  9717]
Street
['Pave' 'Grvl']
Alley
[nan 'Grvl' 'Pave']
LotShape
['Reg' 'IR1' 'IR2' 'IR3']
LandContour
['Lvl' 'Bnk' 'Low' 'HLS']
Utilities
['AllPub' 'NoSeWa']
LotConfig
['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
LandSlope
['Gtl' 

In [63]:
ordinal_label = ['MSZoning','LandSlope','LotConfig','Utilities','LandContour','LotShape','Alley','Street','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
cat = []
for i in ordinal_label:
    unique = traind[i].unique()
    categ = traind[i].astype("category").cat.categories
    cat.append({i:ix for ix,i in enumerate(categ)})
    traind[i] = traind[i].astype("category").cat.codes
    

In [64]:
print(traind)
for i in cat:
    print(i)


        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0        1          60         3         65.0     8450       1     -1   
1        2          20         3         80.0     9600       1     -1   
2        3          60         3         68.0    11250       1     -1   
3        4          70         3         60.0     9550       1     -1   
4        5          60         3         84.0    14260       1     -1   
...    ...         ...       ...          ...      ...     ...    ...   
1455  1456          60         3         62.0     7917       1     -1   
1456  1457          20         3         85.0    13175       1     -1   
1457  1458          70         3         66.0     9042       1     -1   
1458  1459          20         3         68.0     9717       1     -1   
1459  1460          20         3         75.0     9937       1     -1   

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0            3            3          0  ...        

In [65]:
#traind.to_csv('ordinal.csv')

In [66]:
# traind.to_csv('ordinal.csv')
# import pickle
# with open('key_val.pkl','wb') as f:
#     pickle.dump(cat,f)


In [67]:
val

{0: 'C (all)', 1: 'FV', 2: 'RH', 3: 'RL', 4: 'RM'}

In [68]:
for i in testd.columns:
    print(i)
    print(testd[i].unique())

Id
[1461 1462 1463 ... 2917 2918 2919]
MSSubClass
[ 20  60 120 160  80  30  50  90  85 190  45  70  75 180  40 150]
MSZoning
['RH' 'RL' 'RM' 'FV' 'C (all)' nan]
LotFrontage
[ 80.  81.  74.  78.  43.  75.  nan  63.  85.  70.  26.  21.  24. 102.
  94.  90.  79. 110. 105.  41. 100.  67.  60.  73.  92.  84.  39.  88.
  25.  30.  57.  68.  98. 120.  87. 119.  65.  56.  69.  50.  53.  52.
  51.  72.  86. 124.  44.  83.  64.  82.  38.  89.  35.  58.  66.  93.
  31.  76.  28.  61.  95. 129.  59.  77.  96.  47.  34. 117.  48.  62.
  42. 106. 112.  32. 115.  71.  45. 109. 113. 125. 101. 104. 108. 130.
 135.  36.  55. 136.  97.  91.  37.  22. 103.  99.  40. 123.  54. 107.
 150. 160. 195. 128.  33. 118. 134. 155. 126.  46. 149. 200. 121. 131.
 114.  49. 133. 140.]
LotArea
[11622 14267 13830 ...  1894 20000 10441]
Street
['Pave' 'Grvl']
Alley
[nan 'Pave' 'Grvl']
LotShape
['Reg' 'IR1' 'IR2' 'IR3']
LandContour
['Lvl' 'HLS' 'Bnk' 'Low']
Utilities
['AllPub' nan]
LotConfig
['Inside' 'Corner' 'FR2' 'CulD

In [71]:
ordinal_label1 = ['MSZoning','LandSlope','LotConfig','Utilities','LandContour','LotShape','Alley','Street','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
cat1 = []
for i in ordinal_label1:
    unique1 = testd[i].unique()
    categ1 = testd[i].astype("category").cat.categories
    cat1.append({i:ix for ix,i in enumerate(categ1)})
    testd[i] = testd[i].astype("category").cat.codes

In [72]:
print(testd)
for i in cat1:
    print(i)

        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     1461          20         2         80.0    11622       1     -1   
1     1462          20         3         81.0    14267       1     -1   
2     1463          60         3         74.0    13830       1     -1   
3     1464          60         3         78.0     9978       1     -1   
4     1465         120         3         43.0     5005       1     -1   
...    ...         ...       ...          ...      ...     ...    ...   
1454  2915         160         4         21.0     1936       1     -1   
1455  2916         160         4         21.0     1894       1     -1   
1456  2917          20         3        160.0    20000       1     -1   
1457  2918          85         3         62.0    10441       1     -1   
1458  2919          60         3         74.0     9627       1     -1   

      LotShape  LandContour  Utilities  ...  ScreenPorch  PoolArea  PoolQC  \
0            3            3          0  ...  

In [73]:
testd.to_csv('ordinal_test.csv')
# import pickle
# with open('key_val.pkl','wb') as f:
#     pickle.dump(cat,f)
